name: Publish docs to Wiki

on:
  push:
    paths:
      - documents/wiki/**
    branches:
      - main

env:
  USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }}
  USER_NAME: "timchan-aitherentertainment"
  USER_EMAIL: tim.chan@aitherentertainment.com
  OWNER: ${{ github.event.repository.owner.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  publish_to_wiki:
    name: Publish to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull from wiki
        run: |
            mkdir folder
            cd folder
            git init
            git config user.name $USER_NAME
            git config user.email $USER_EMAIL
            git pull https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git
          
      - name: Push to wiki
        run: |
            rsync -av --delete documents/wiki/ folder/ --exclude .git
            cd folder
            git add .
            git commit -m "docs: update wiki" 
            git push -f -u https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git master